ni = int(input('Informe um número inteiro: '))
print('-'*13)
print('Tabuada do {}'.format(ni))
print('-'*13)
print('{} x {:2} = {}'.format(ni, 1, ni*1))
print('{} x {:2} = {}'.format(ni, 2, ni*2))
print('{} x {:2} = {}'.format(ni, 3, ni*3))
print('{} x {:2} = {}'.format(ni, 4, ni*4))
print('{} x {:2} = {}'.format(ni, 5, ni*5))
print('{} x {:2} = {}'.format(ni, 6, ni*6))
print('{} x {:2} = {}'.format(ni, 7, ni*7))
print('{} x {:2} = {}'.format(ni, 8, ni*8))
print('{} x {:2} = {}'.format(ni, 9, ni*9))
print('{} x {:2} = {}'.format(ni, 10, ni*10))
print('-'*13)
